---
name: pre-commit

on:
    pull_request:
        branches:
            - main

jobs:
    pre-commit:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
            
            - name: Lint Python code
              uses: pre-commit/action@v3.0.1
              with:
                pre-commit_hooks: "flake8, black, isort"
                args: --files $(git ls-files -- app/)